## -*- Makefile -*-
##
## User: Spiros Delviniotis
##
##

#### Compiler and tool definitions shared by all build targets #####
MPI_original: mpi_heat2D.c
	mpicc -o MPI_original mpi_heat2D.c

clean:
	rm -f MPI_original
