## -*- Makefile -*-
##
## User: Spiros Delviniotis
##
##

#### Compiler and tool definitions shared by all build targets #####
MPI_main: MPI_main.c
	mpicc -o MPI_main MPI_main.c -lm

clean:
	rm -f MPI_main
